### ISSUE TITLE
Doesn't this just import the prebuilt css ?

### ISSUE THREAD

**Issue by crucialfelix** [tachyons-css/tachyons-webpack#2]
Hello - Doesn't this just import the prebuilt tachyons.css ?

I was expecting/wanting to use webpack to compile my customized tachyons.

Or does it do that and I am misunderstanding the example ?
- thanks

**Comment by garrensmith** [comment]
Hi @crucialfelix it just imports the prebuilt tachyons. The idea is to be a simple base for doing some prototyping with tachyons. You can add your customised tachyons code in the `index.css` and that will override the default tachyons css. Or you could change the webpack config to more suit your needs.

**Comment by crucialfelix** [comment]
Ah okay. tbh that doesn't seem like much of a help, it is too simple.

`tachyons-webpack` sounds like it would build tachyons, not just include a css file.

The customizing  and building of tachyons is much harder. I was unable to figure out which custom-media / var / nextcss etc. was supposed to be in the plugins stack (it isn't shown in tachyons repo).

I eventually just gave up and do a separate tachyons build outside of webpack.

thanks

**Comment by shinzui** [comment]
@crucialfelix You need to replicate [tachyons-build-css](https://github.com/tachyons-css/tachyons-build-css) in your webpack build to get it working.

@garrensmith I agree with @crucialfelix, this is not very useful. I expected this project to replicate [tachyons-build-css](https://github.com/tachyons-css/tachyons-build-css) in order to allow a better hacking experience. Any serious project using tachyons needs to customize it using PostCSS, so at the very least this project's webpack config should support that. 

Also, I think that the official tachyons-build-css should switch to webpack – it's just more productive.

**Comment by garrensmith** [comment]
I'll happily accept any PR that make this more useful.

**Comment by des-des** [comment]
Here is an example building tachyons: https://github.com/des-des/tachyons-webpack-boilerplate
